# Generated by Django 2.0.5 on 2018-09-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='确认码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_user_rate', models.IntegerField(default=-1, verbose_name='发单评分')),
                ('receive_user_rate', models.IntegerField(default=-1, verbose_name='接单评分')),
                ('express_number', models.CharField(max_length=30, verbose_name='快递单号')),
                ('express_company', models.CharField(max_length=20, verbose_name='快递公司')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('status', models.CharField(default='publish', max_length=30, verbose_name='状态')),
                ('pub_date', models.DateTimeField(verbose_name='发布时间')),
                ('receive_date', models.DateTimeField(blank=True, null=True, verbose_name='接单时间')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('express_height', models.IntegerField(verbose_name='是否超重')),
                ('height_cost', models.FloatField(verbose_name='超重费用')),
                ('hurry_cost', models.FloatField(verbose_name='加急费用')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('latest_time', models.DateTimeField(verbose_name='期望收货时间')),
                ('contact', models.CharField(max_length=20, verbose_name='联系方式')),
                ('tip_cost', models.FloatField(verbose_name='小费')),
                ('total_cost', models.FloatField(verbose_name='总价')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='邮箱认证')),
                ('credit', models.IntegerField(default=10, verbose_name='信誉度')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('verify', models.CharField(default=-1, max_length=32, verbose_name='实名认证')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='express',
            name='publish_user',
            field=models.ManyToManyField(related_name='publish_user', to='Express.User', verbose_name='发单者'),
        ),
        migrations.AddField(
            model_name='express',
            name='receive_user',
            field=models.ManyToManyField(related_name='receive_user', to='Express.User', verbose_name='接单者'),
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Express.User', verbose_name='关联的用户'),
        ),
    ]
